src/main/java/cn/wmyskxz/pojo/Product.java
package cn.wmyskxz.pojo;

public class Product {
	private Integer id;

	private String name;

	private String sub_title;

	private Float price;

	private Integer sale;

	private Integer stock;

	private Integer category_id;

	private Integer reviewCount;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	public String getSub_title() {
		return sub_title;
	}

	public void setSub_title(String sub_title) {
		this.sub_title = sub_title == null ? null : sub_title.trim();
	}

	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Integer getSale() {
		return sale;
	}

	public void setSale(Integer sale) {
		this.sale = sale;
	}

	public Integer getStock() {
		return stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Integer getCategory_id() {
		return category_id;
	}

	public void setCategory_id(Integer category_id) {
		this.category_id = category_id;
	}

	public Integer getReviewCount() {
		return reviewCount;
	}

	public void setReviewCount(Integer reviewCount) {
		this.reviewCount = reviewCount;
	}

	public Integer getSaleXReviewCount() {
		return this.reviewCount * this.sale;
	}
}

src/main/java/cn/wmyskxz/pojo/User.java
package cn.wmyskxz.pojo;

public class User {
	private Integer id;

	private String name;

	private String password;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	public String getAnonymousName() {
		if (name == null){
			return null;
		}
		if (name.length() <= 1){
			return "*";
		}
		if (name.length() == 2){
			return name.substring(0, 1) + "*";
		}

		char[] cs = name.toCharArray();
		for (int i = 1; i < cs.length - 1; i++) {
			cs[i] = '*';
		}
		return new String(cs);
	}
}

src/main/java/cn/wmyskxz/controller/ProductController.java
package cn.wmyskxz.controller;

import cn.wmyskxz.pojo.Category;
import cn.wmyskxz.pojo.Product;
import cn.wmyskxz.pojo.ProductImage;
import cn.wmyskxz.service.CategoryService;
import cn.wmyskxz.service.ProductImageService;
import cn.wmyskxz.service.ProductService;
import cn.wmyskxz.service.PropertyValueService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpServletRequest;
import java.io.File;
import java.util.List;

/**
 * Product 控制器
 *
 * @author: @我没有三颗心脏
 * @create: 2018-04-27-下午 20:21
 */
@Controller
@RequestMapping("/admin")
public class ProductController {

	@Autowired
	CategoryService categoryService;

	@Autowired
	ProductService productService;

	@Autowired
	ProductImageService productImageService;

	@Autowired
	PropertyValueService propertyValueService;

	@RequestMapping("/listProduct")
	public String list(Model model, Integer category_id) {
		List<Product> products = productService.list(category_id);
		model.addAttribute("products", products);
		Category category = categoryService.get(category_id);
		model.addAttribute("category", category);
		return "admin/listProduct";
	}

	@RequestMapping("/addProduct")
	public String add(Product product) {
		productService.add(product);

		// 创建新的 Product 时默认创建 5 个对应的 ProductImage 数据
		ProductImage productImage = new ProductImage();
		productImage.setProduct_id(product.getId());
		for (int i = 1; i <= 5; i++) {
			productImageService.add(productImage);
		}

		return "redirect:listProduct?category_id=" + product.getCategory_id();
	}

	@RequestMapping("/deleteProduct")
	public String delete(Integer id, HttpServletRequest request) {

		// 在删除产品的时候将对应的 5 个 ProductImage 数据也删除了
		productImageService.deleteByProductId(id);
		// 同时删除目录下的相关文件
		String path = request.getSession().getServletContext().getRealPath("" + id);
		deleteDir(new File(path));

		// 删除外键对应的数据
		propertyValueService.deleteByProductId(id);

		int category_id = productService.get(id).getCategory_id();
		productService.delete(id);

		return "redirect:listProduct?category_id=" + category_id;
	}

	/**
	 * 递归删除目录下的所有文件及子目录下所有文件
	 *
	 * @param dir 将要删除的文件目录
	 * @return boolean Returns "true" if all deletions were successful.
	 * If a deletion fails, the method stops attempting to
	 * delete and returns "false".
	 */
	private static boolean deleteDir(File dir) {
		if (dir.isDirectory()) {
			String[] children = dir.list();
			//递归删除目录中的子目录下
			for (int i = 0; i < children.length; i++) {
				boolean success = deleteDir(new File(dir, children[i]));
				if (!success) {
					return false;
				}
			}
		}
		// 目录此时为空，可以删除
		return dir.delete();
	}

	@RequestMapping("/editProduct")
	public String edit(Integer id, Model model) {
		Product product = productService.get(id);
		model.addAttribute("product", product);
		Category category = categoryService.get(product.getCategory_id());
		model.addAttribute("category", category);
		return "admin/editProduct";
	}

	@RequestMapping("/updateProduct")
	public String update(Product product) {
		productService.update(product);
		return "redirect:listProduct?category_id=" + product.getCategory_id();
	}
}

src/main/webapp/WEB-INF/views/alipay.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" isELIgnored="false" %>

<%@include file="include/header.jsp" %>
<%@include file="include/top.jsp" %>

<style>
    div.aliPayPageDiv{
        text-align: center;
        padding-bottom: 40px;
        max-width: 1013px;
        margin: 10px auto;
    }
    div.aliPayPageLogo{
        margin: 20px;
    }
    span.confirmMoneyText{
        color: #4D4D4D;
    }
    span.confirmMoney{
        display: block;
        color: #FF6600;
        font-weight: bold;
        font-size: 20px;
        margin: 10px;
    }
    button.confirmPay{
        background-color: #00AAEE;
        border: 1px solid #00AAEE;
        text-align: center;
        line-height: 31px;
        font-size: 14px;
        font-weight: 700;
        color: white;
        width: 107px;
        margin-top: 20px;
    }

    img.aliPayImg {
        width: 300px;
    }
</style>
<div class="aliPayPageDiv">
    <div class="aliPayPageLogo">
        <img class="pull-left" src="img/fore/simpleLogo.png">
        <div style="clear:both"></div>
    </div>

    <div>
        <span class="confirmMoneyText">扫一扫付款（元）</span>
        <span class="confirmMoney">
		￥${param.total}</span>

    </div>
    <div>
        <img class="aliPayImg" src="img/fore/alipay2wei.jpg">
    </div>


    <div>
        <a href="payed?order_id=${param.order_id}&total=${param.total}">
            <button class="confirmPay">确认支付</button>
        </a>
    </div>

</div>

src/main/webapp/WEB-INF/views/bought.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" isELIgnored="false" %>

<%@include file="include/header.jsp" %>
<%@include file="include/top.jsp" %>
<%@include file="include/mini-search.jsp" %>

<style>
    div.boughtDiv {
        max-width: 1013px;
        margin: 10px auto;
    }

    div.orderType div {
        border-bottom: 2px solid #E8E8E8;
        float: left;
    }

    div.orderType a {
        border-right: 1px solid #E8E8E8;
        display: inline-block;
        font-size: 16px;
        font-weight: bold;
        color: black;
        margin-bottom: 10px;
        padding: 0px 20px;
        text-decoration: none;
    }

    div.orderType a:hover {
        color: #FF0036;
        text-decoration: none;
    }

    div.orderType div.selectedOrderType {
        border-bottom: 2px solid #FF0036;
    }

    div.orderType div.selectedOrderType a {
        color: #FF0036;
    }

    div.orderTypeLastOne {
        overflow: hidden;
        float: none !important;
        border-bottom: 2px solid #E8E8E8;
        height: 35px;
    }

    a.noRightborder {
        border-right-width: 0px !important;
    }

    table.orderListTitleTable {
        border: 1px solid #E8E8E8;
        width: 100%;
        margin: 20px 0px;
        background-color: #F5F5F5;
        text-align: center;
        font-size: 12px;
    }

    table.orderListTitleTable td {
        padding: 12px 0px;
    }

    div.boughtDiv {
        max-width: 1013px;
        margin: 10px auto;
    }

    table.orderListItemTable {
        border: 2px solid #ECECEC;
        width: 100%;
        margin: 20px 0px;
        font-size: 12px;
    }

    table.orderListItemTable:hover {
        border: 2px solid #aaa !important;
    }

    table.orderListItemTable td {
        padding: 8px 10px;
    }

    tr.orderListItemFirstTR {
        background-color: #F1F1F1;
    }

    div.orderItemWangWangGif {
        display: inline-block;
        width: 67px;
        height: 22px;
        background-image: url(img/fore/wangwang.gif);
        background-repeat: no-repeat;
        background-color: transparent;
        background-attachment: scroll;
        background-position: -0px -0px;
        position: relative;
        top: 0px;
        left: 2px;
    }

    td.orderItemDeleteTD {
        text-align: right;
    }

    span.orderListItemDelete {
        display: inline-block;
        margin: 0px 10px;
        color: #999999;
        font-size: 16px;
    }

    div.orderListItemProductLinkOutDiv {
        position: relative;
        height: 80px;
    }

    div.orderListItemProductLinkInnerDiv {
        position: absolute;
        bottom: 0px;
    }

    div.orderListItemProductOriginalPrice {
        color: #999999;
        font-size: 14px;
    }

    div.orderListItemProductPrice {
        color: #3C3C3C;
        font-size: 14px;
    }

    td.orderListItemNumberTD {
        text-align: center;
    }

    td.orderItemOrderInfoPartTD {
        border: solid 1px #ECECEC;
    }

    span.orderListItemNumber {
        color: #3C3C3C;
    }

    td.orderListItemProductRealPriceTD {
        text-align: center;
    }

    div.orderListItemProductRealPrice {
        color: #3C3C3C;
        font-size: 14px;
        font-weight: bold;
    }

    div.orderListItemPriceWithTransport {
        color: #6C6C6C;
        font-size: 12px;
    }

    td.orderListItemButtonTD {
        text-align: center;
    }

    button.orderListItemReview {
        border: 1px solid #DCDCDC;
        background-color: #fff;
        border-radius: 2px;
        color: #3C3C3C;
        font-size: 12px;
        font-weight: bold;
        padding: 6px 12px;
    }

    button.orderListItemReview:hover {
        border-color: #C40000;
        color: #C40000;
    }

    button.orderListItemConfirm {
        background-color: #66B6FF;
        border-radius: 2px;
        color: white;
        font-size: 12px;
        font-weight: bold;
        border-width: 0px;
        padding: 6px 12px;
    }

    button.orderListItemConfirm:hover {
        background-color: #118ADB;
    }

    a {
        color: #999;
    }

    a:hover {
        text-decoration: none;
        color: #FF0036;
    }
</style>

<script>
    var deleteOrder = false;
    var deleteOrderid = 0;

    $(function () {
        $("a[orderStatus]").click(function () {
            var orderStatus = $(this).attr("orderStatus");
            if ('all' == orderStatus) {
                $("table[orderStatus]").show();
            }
            else {
                $("table[orderStatus]").hide();
                $("table[orderStatus=" + orderStatus + "]").show();
            }

            $("div.orderType div").removeClass("selectedOrderType");
            $(this).parent("div").addClass("selectedOrderType");
        });

        $("a.deleteOrderLink").click(function () {
            deleteOrderid = $(this).attr("oid");
            deleteOrder = false;
            $("#deleteConfirmModal").modal("show");
        });

        $("button.deleteConfirmButton").click(function () {
            deleteOrder = true;
            $("#deleteConfirmModal").modal('hide');
        });

        $('#deleteConfirmModal').on('hidden.bs.modal', function (e) {
            if (deleteOrder) {
                var page = "deleteOrder";
                $.post(
                    page,
                    {"order_id": deleteOrderid},
                    function (result) {
                        if ("success" == result) {
                            $("table.orderListItemTable[oid=" + deleteOrderid + "]").hide();
                        }
                        else {
                            location.href = "login.jsp";
                        }
                    }
                );

            }
        })

        $(".ask2delivery").click(function () {
            var link = $(this).attr("link");
            $(this).hide();
            page = link;
            $.ajax({
                url: page,
                success: function (result) {
                    alert("卖家已秒发，刷新当前页面，即可进行确认收货")
                }
            });

        });
    });

</script>

<div class="boughtDiv">
    <div class="orderType">
        <div class="selectedOrderType"><a orderStatus="all" href="#nowhere">所有订单</a></div>
        <div><a orderStatus="waitPay" href="#nowhere">待付款</a></div>
        <div><a orderStatus="waitDelivery" href="#nowhere">待发货</a></div>
        <div><a orderStatus="waitConfirm" href="#nowhere">待收货</a></div>
        <div><a orderStatus="waitReview" href="#nowhere" class="noRightborder">待评价</a></div>
        <div class="orderTypeLastOne"><a class="noRightborder"> </a></div>
    </div>
    <div style="clear:both"></div>
    <div class="orderListTitle">
        <table class="orderListTitleTable">
            <tr>
                <td>宝贝</td>
                <td width="121px">单价</td>
                <td width="121px">数量</td>
                <td width="141px">实付款</td>
                <td width="121px">交易操作</td>
            </tr>
        </table>

    </div>

    <div class="orderListItem">
        <c:forEach items="${orders}" var="o">
            <table class="orderListItemTable" orderStatus="${o.status}" oid="${o.id}">
                <tr class="orderListItemFirstTR">
                    <td colspan="2">
                        <b>${o.create_date}</b>
                        <span>订单号: ${o.order_code}
                    </span>
                    </td>
                    <td colspan="2"><img width="13px" src="img/fore/orderItemTmall.png">天猫商场</td>
                    <td colspan="1">
                        <a class="wangwanglink" href="#nowhere">
                            <div class="orderItemWangWangGif"></div>
                        </a>

                    </td>
                    <td class="orderItemDeleteTD">
                        <a class="deleteOrderLink" oid="${o.id}" href="#nowhere">
                            <span class="orderListItemDelete glyphicon glyphicon-trash"></span>
                        </a>

                    </td>
                </tr>
                <c:forEach items="${o.orderItems}" var="oi" varStatus="st">
                    <tr class="orderItemProductInfoPartTR">
                        <td class="orderItemProductInfoPartTD"><img width="80" height="80"
                                                                    src="img/product/${oi.product.id}/1.jpg">
                        </td>
                        <td class="orderItemProductInfoPartTD">
                            <div class="orderListItemProductLinkOutDiv">
                                <a href="foreproduct?pid=${oi.product.id}">${oi.product.name}</a>
                                <div class="orderListItemProductLinkInnerDiv">
                                    <img src="img/fore/creditcard.png" title="支持信用卡支付">
                                    <img src="img/fore/7day.png" title="消费者保障服务,承诺7天退货">
                                    <img src="img/fore/promise.png" title="消费者保障服务,承诺如实描述">
                                </div>
                            </div>
                        </td>
                        <td class="orderItemProductInfoPartTD" width="100px">

                            <div class="orderListItemProductOriginalPrice">￥${oi.product.price}</div>
                            <div class="orderListItemProductPrice">￥${oi.product.price}</div>

                        </td>
                        <c:if test="${st.count==1}">

                            <td valign="top" rowspan="${fn:length(o.orderItems)}"
                                class="orderListItemNumberTD orderItemOrderInfoPartTD" width="100px">
                                <span class="orderListItemNumber">${o.totalNumber}</span>
                            </td>
                            <td valign="top" rowspan="${fn:length(o.orderItems)}" width="120px"
                                class="orderListItemProductRealPriceTD orderItemOrderInfoPartTD">
                                <div class="orderListItemProductRealPrice">￥${o.total}</div>
                                <div class="orderListItemPriceWithTransport">(含运费：￥0.00)</div>
                            </td>
                            <td valign="top" rowspan="${fn:length(o.orderItems)}"
                                class="orderListItemButtonTD orderItemOrderInfoPartTD" width="100px">
                                <c:if test="${o.status=='waitConfirm' }">
                                    <a href="confirmPay?order_id=${o.id}">
                                        <button class="orderListItemConfirm">确认收货</button>
                                    </a>
                                </c:if>
                                <c:if test="${o.status=='waitPay' }">
                                    <a href="alipay.jsp?order_id=${o.id}&total=${o.total}">
                                        <button class="orderListItemConfirm">付款</button>
                                    </a>
                                </c:if>

                                <c:if test="${o.status=='waitDelivery' }">
                                    <span>待发货</span>
                                    <%--                                     <button class="btn btn-info btn-sm ask2delivery" link="admin_order_delivery?id=${o.id}">催卖家发货</button> --%>

                                </c:if>

                                <c:if test="${o.status=='waitReview' }">
                                    <a href="review?order_id=${o.id}">
                                        <button class="orderListItemReview">评价</button>
                                    </a>
                                </c:if>
                            </td>
                        </c:if>
                    </tr>
                </c:forEach>

            </table>
        </c:forEach>

    </div>

</div>


<%@include file="include/footer.jsp" %>

src/main/webapp/WEB-INF/views/orderConfirmedPage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" isELIgnored="false"%>

<%@include file="include/header.jsp" %>
<%@include file="include/top.jsp" %>
<%@include file="include/mini-search.jsp" %>

<style>
    div.orderFinishDiv{
        border: 1px solid #E5E5E5;
        padding: 40px;
        max-width: 1013px;
        margin: 10px auto;
    }
    div.orderFinishDiv span{
        font-size: 14px;
        color: black;
        font-weight: bold;
        margin-left: 20px;
        padding-top: 20px;
    }
</style>

<div class="orderFinishDiv">
    <div class="orderFinishTextDiv">
        <img src="img/fore/orderFinish.png">
        <span>交易已经成功，卖家将收到您的货款。</span>
    </div>
</div>

<%@include file="include/footer.jsp" %>

src/main/webapp/WEB-INF/views/registerSuccessPage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" isELIgnored="false" %>
<%@include file="include/header.jsp" %>
<%@include file="include/top.jsp" %>
<%@include file="include/mini-search.jsp" %>

<style>
    .page {
        width: 990px;
        margin: 90px auto;
        color: #3c3c3c;
        font: 400 12px/1.6 arial, 'Hiragino Sans GB', 宋体, sans-serif;
    }

    .content {
        border-top: 2px solid #e6e6e6;
        padding: 50px 0;
    }

    .form-main-list {
        width: 720px;
    }

    .form-list {
        margin: 0 auto;
        font-size: 14px;
    }

    .form-group {
        padding: 10px 0;
    }

    .form-item input {
        float: left;
        width: 300px;
        border: 1px solid #dedede;
        height: 37px;
        line-height: 37px;
        padding: 9px;
        font-size: 14px;
        _margin-left: -3px;
    }

    .registerSuccessMessage {
        width: 300px;
        margin: 20px auto;
        text-align: center;
    }
</style>
<%--<div class="page">--%>
    <%--<div class="content">--%>
        <%--<div class="form-list form-main-list">--%>
            <%--<div class="form-group">--%>

            <%--</div>--%>
        <%--</div>--%>
    <%--</div>--%>
<%--</div>--%>
<div style="margin-top: 90px;height: 0;"></div>
<div class="registerSuccessMessage">
    <div class="alert alert-success">
        <span class="glyphicon glyphicon-ok-sign"></span>
        恭喜注册成功
    </div>
</div>
<%@include file="include/footer.jsp" %>

src/main/webapp/WEB-INF/views/reviewPage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8" isELIgnored="false" %>

<%@include file="include/header.jsp" %>
<%@include file="include/top.jsp" %>
<%@include file="include/mini-search.jsp" %>
<style>
    div.reviewDiv {
        max-width: 1013px;
        margin: 10px auto;
    }

    div.reviewProductInfoImg {
        border: 1px solid #E7E7E7;
        width: 464px;
        text-align: center;
        float: left;
    }

    div.reviewProductInfoRightDiv {
        overflow: hidden;
        border-top: 1px solid #E7E7E7;
        padding: 30px 20px;
    }

    div.reviewProductInfoRightText {
        color: black;
        font-size: 16px;
        font-weight: bold;
    }

    table.reviewProductInfoTable {
        margin: 20px 10px;
        font-size: 12px;
    }

    table.reviewProductInfoTable td {
        padding-bottom: 5px;
        color: #999999;
    }

    span.reviewProductInfoTablePrice {
        color: #FF0036;
        font-size: 20px;
        font-weight: bold;
    }

    span.reviewProductInfoTableSellNumber {
        color: #FF0036;
        font-size: 14px;
        font-weight: bold;
    }

    div.reviewProductInfoRightBelowDiv {
        border: 1px solid #F6F5F3;
        background-color: #FDFBFA;
        height: 166px;
        padding: 16px 0px 16px 81px;
    }

    span.reviewProductInfoRightBelowImg {
        background-color: white;
        border: 1px solid #E1E1E1;
        display: inline-block;
        width: 23px;
        height: 42px;
        background-image: url(/img/fore/reviewLight.png);
        background-repeat: no-repeat;
        padding: 0px;
    }

    img {
        vertical-align: baseline;
    }

    span.reviewProductInfoRightBelowText {
        border: 1px solid #EFEFEF;
        display: inline-block;
        width: 200px;
        height: 42px;
        padding: 4px;
        position: relative;
        left: -4px;
        top: -5px;
        color: #666666;
        font-size: 12px;
    }

    div.reviewStasticsDiv {
        margin-top: 20px;
    }

    div.reviewStasticsLeft {
        width: 180px;
        float: left;
    }

    div.reviewStasticsLeftTop {
        background-color: #FF0036;
        height: 6px;
    }

    div.reviewStasticsLeftContent {
        line-height: 29px;
        border-left: 1px solid #D5D4D4;
        border-right: 1px solid #D5D4D4;
        background-color: #F6F5F1;
        text-align: center;
        font-size: 14px;
        color: #363535;
        font-weight: bold;
    }

    div.reviewStasticsLeftFoot {
        height: 6px;
        border-left: 1px solid #D5D4D4;
        border-bottom: 1px solid #D5D4D4;
        background-color: #F6F5F1;
    }

    span.reviewStasticsNumber {
        color: #284CA5;
    }

    div.reviewStasticsRight {
        overflow: hidden;
    }

    div.reviewStasticsRightEmpty {
        height: 35px;
    }

    div.reviewStasticsFoot {
        background-color: #F6F5F1;
        border: 1px solid #D5D4D4;
        border-left-width: 0px;
        height: 6px;
    }

    div.makeReviewDiv {
        border: 1px solid #D1CCC8;
        margin: 20px 0px;
        background-color: #EFEFEF;
    }

    div.makeReviewText {
        font-size: 16px;
        color: #333333;
        font-weight: bold;
        margin: 20px 40px;
    }

    table.makeReviewTable {
        margin: 20px 40px;
        font-size: 12px;
    }

    table.makeReviewTable td {
        border: 1px solid #E7E7E7;
        padding: 10px;
        background-color: white;
    }

    table.makeReviewTable textarea {
        border-width: 0px;
        resize: none;
        width: 420px;
        height: 120px;
    }

    td.makeReviewTableFirstTD {
        background-color: #F6F6F6;
    }

    div.makeReviewButtonDiv {
        background-color: white;
        text-align: center;
        padding: 15px;
    }

    div.makeReviewButtonDiv button {
        width: 72px;
        height: 26px;
        border-radius: 2px;
        background-color: #FF0036;
        color: white;
        border-width: 0px;
        font-weight: bold;
    }

    div.reviewDate {
        width: 100px;
    }

    div.reviewDivlistReviewsEach div {
        display: inline-block;
    }

    div.reviewDate {
        color: #CCCCDD;
    }

    div.reviewContent {
        color: #333333;
        width: 698px;
    }

    div.reviewUserInfo {
        color: #333333;
    }

    div.reviewDivlistReviewsEach {
        padding: 20px;
        border-bottom: 1px solid #ECECEC;
    }

    span.reviewUserInfoAnonymous {
        color: #CCCCDD;
        margin-left: 5px;
    }
</style>

<div class="reviewDiv">
    <div class="reviewProductInfoDiv">
        <div class="reviewProductInfoImg"><img width="400px" height="400px" src="img/product/${product.id}/1.jpg"></div>
        <div class="reviewProductInfoRightDiv">
            <div class="reviewProductInfoRightText">
                ${product.name}
            </div>
            <table class="reviewProductInfoTable">
                <tr>
                    <td width="75px">价格:</td>
                    <td><span class="reviewProductInfoTablePrice">￥${product.price}</span> 元</td>
                </tr>
                <tr>
                    <td>配送</td>
                    <td>快递: 0.00</td>
                </tr>
                <tr>
                    <td>月销量:</td>
                    <td><span class="reviewProductInfoTableSellNumber">${product.sale}</span> 件</td>
                </tr>
            </table>

            <div class="reviewProductInfoRightBelowDiv">
                <span class="reviewProductInfoRightBelowImg"><img src="img/fore/reviewLight.png"></span>
                <span class="reviewProductInfoRightBelowText"
                      style="margin-top: 2px;">现在查看的是 您所购买商品的信息于${order.create_date}下单购买了此商品 </span>
            </div>
        </div>
        <div style="clear:both"></div>
    </div>
    <div class="reviewStasticsDiv">
        <div class="reviewStasticsLeft">
            <div class="reviewStasticsLeftTop"></div>
            <div class="reviewStasticsLeftContent">累计评价 <span
                    class="reviewStasticsNumber"> ${product.reviewCount}</span></div>
            <div class="reviewStasticsLeftFoot"></div>
        </div>
        <div class="reviewStasticsRight">
            <div class="reviewStasticsRightEmpty"></div>
            <div class="reviewStasticsFoot"></div>
        </div>
    </div>

    <c:if test="${param.showonly==true}">
        <div class="reviewDivlistReviews">
            <c:forEach items="${reviews}" var="r">
                <div class="reviewDivlistReviewsEach">
                    <div class="reviewDate">${r.createDate}</div>
                    <div class="reviewContent">${r.content}</div>
                    <div class="reviewUserInfo pull-right">${r.user.anonymousName}<span class="reviewUserInfoAnonymous">(匿名)</span>
                    </div>
                </div>
            </c:forEach>
        </div>
    </c:if>

    <c:if test="${param.showonly!=true}">
        <div class="makeReviewDiv">
            <form method="post" action="doreview">
                <div class="makeReviewText">其他买家，需要你的建议哦！</div>
                <table class="makeReviewTable">
                    <tr>
                        <td class="makeReviewTableFirstTD">评价商品</td>
                        <td><textarea name="content"></textarea></td>
                    </tr>
                </table>
                <div class="makeReviewButtonDiv">
                    <input type="hidden" name="order_id" value="${order.id}">
                    <input type="hidden" name="product_id" value="${product.id}">
                    <button type="submit">提交评价</button>
                </div>
            </form>
        </div>
    </c:if>
</div>

<%@include file="include/footer.jsp"%>

src/main/webapp/WEB-INF/views/test.jsp
<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2018/5/3 0003
  Time: 上午 9:00
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>

</body>
</html>